name: LoQi Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build application for Windows
        run: |
          pyinstaller --onefile --windowed --icon ASSETS/PortF.ico --add-data "ASSETS/PortF.ico;." src/GHP.py
          mkdir -p dist/windows
          mv dist/GHP.exe dist/windows/GHP.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-application
          path: dist/windows

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Convert ICO to ICNS (macOS)
        run: |
          sips -s format png ASSETS/PortF.ico --out ASSETS/icon_256x256.png
          mkdir ASSETS/icon.iconset
          mv ASSETS/icon_256x256.png ASSETS/icon.iconset/icon_256x256.png
          iconutil -c icns ASSETS/icon.iconset -o ASSETS/PortF.icns
          rm -rf ASSETS/icon.iconset

      - name: Build application for macOS
        run: |
          pyinstaller --onefile --windowed --icon ASSETS/PortF.icns --add-data "ASSETS/PortF.icns:." src/GHP.py
          mkdir -p dist/mac
          mv dist/GHP.app dist/mac/GHP.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-application
          path: dist/mac

  deploy-to-gh-pages:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g markdown-to-html-cli

      - name: Convert README to HTML
        run: markdown-to-html -i README.md -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./