name: LoQi Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.9]

    steps:
      - name: Set up working directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/dist $GITHUB_WORKSPACE/ASSETS
          mv * $GITHUB_WORKSPACE/ASSETS  # Move all files to ASSETS folder
          cd $GITHUB_WORKSPACE/ASSETS

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Copy icon from ASSETS folder
        run: cp PortF.ico $GITHUB_WORKSPACE

      - name: Install dependencies
        run: python -m pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Build application
        run: |
          cd $GITHUB_WORKSPACE/ASSETS  # Move back to ASSETS folder
          pyinstaller --onefile --icon=PortF.ico GHP.py
          mv dist/* $GITHUB_WORKSPACE/dist/application  # Move artifacts to dist folder

      - name: Save artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: application-${{ matrix.os }}-python-${{ matrix.python-version }}
          path: $GITHUB_WORKSPACE/dist
