name: LoQi Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.10]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }
        shell: pwsh

      - name: Copy Icon from ASSETS Folder
        run: |
          if [ -f "${GITHUB_WORKSPACE}/ASSETS/PortF.ico" ]; then
            cp "${GITHUB_WORKSPACE}/ASSETS/PortF.ico" .
          fi
        shell: bash

      - name: Copy Icon from ASSETS Folder (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path "${GITHUB_WORKSPACE}/ASSETS/PortF.ico") {
            Copy-Item "${GITHUB_WORKSPACE}/ASSETS/PortF.ico" -Destination "."
          }
        shell: pwsh

      - name: Build Application
        run: |
          pyinstaller --onefile --icon=PortF.ico GHP.py
          mv dist/application GHP
        continue-on-error: false

      - name: Organize Artifacts
        run: |
          $destDir = "${GITHUB_WORKSPACE}/dist/${{ matrix.os }}/application"
          New-Item -ItemType Directory -Force -Path $destDir
          mv GHP $destDir
        shell: pwsh

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: application-${{ matrix.os }}-python-${{ matrix.python-version }}
          path: dist/${{ matrix.os }}

      - name: Notify Build Completion
        if: always()
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Build completed: ${{ job.status }}'
            })
