name: LoQi Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 requests

      - name: Copy assets
        run: |
          mkdir -p ASSETS
          cp ASSETS/fav.PNG ASSETS/PortF.ico ./

      - name: Build application for macOS
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile --windowed --icon PortF.ico --add-data "fav.PNG:." --add-data "PortF.ico:." GHP.py
          mkdir -p dist/mac
          mv dist/GHP.app dist/mac/GHP.app

      - name: Build application for Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --windowed --icon PortF.ico --add-data "fav.PNG;." --add-data "PortF.ico;." GHP.py
          mkdir -p dist/windows
          mv dist/GHP.exe dist/windows/GHP.exe

      - name: Save artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: application-${{ matrix.os }}-python-${{ matrix.python-version }}
          path: dist/