name: LoQi Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Copy icon from ASSETS folder
        run: cp ${{ github.workspace }}/ASSETS/PortF.ico ./

      - name: Build application
        run: |
          pip install -r requirements.txt
          pyinstaller --onefile --icon=PortF.ico GHP.py
          mkdir -p $GITHUB_WORKSPACE/dist
          mv dist/* $GITHUB_WORKSPACE/dist

      - name: Save artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: application-${{ matrix.os }}-python-${{ matrix.python-version }}
          path: $GITHUB_WORKSPACE/dist
