name: LoQi Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.10]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Copy Icon from ASSETS Folder
        run: |
          Copy-Item "${GITHUB_WORKSPACE}/ASSETS/PortF.ico" -Destination "."
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Build Application
        run: pyinstaller --onefile --icon=PortF.ico GHP.py
        continue-on-error: false

      - name: Organize Artifacts
        run: |
          $destDir = "${GITHUB_WORKSPACE}/dist/${{ matrix.os }}/application"
          New-Item -ItemType Directory -Force -Path $destDir
          Get-ChildItem 'dist/*' -Exclude "${{ matrix.os }}" | Move-Item -Destination $destDir
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: application-${{ matrix.os }}-python-${{ matrix.python-version }}
          path: ${GITHUB_WORKSPACE}/dist/${{ matrix.os }}
