name: LoQi Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    env:
      PORTF: ${{ secrets.PF_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyqt5 pyqtwebengine

      - name: Set up environment variables
        run: |
          echo "PORTF=${{ secrets.PF_TOKEN }}" >> $GITHUB_ENV

      - name: Create secret
        run: |
          echo ${{ secrets.PF_TOKEN }} > token.txt
          gh secret set PF_TOKEN --body token.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build application
        run: |
          pyinstaller --onefile main.py
          mv dist/* $GITHUB_WORKSPACE/dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: $GITHUB_WORKSPACE/dist
